### ISSUE TITLE
Unable to connect 

### ISSUE THREAD

**Issue by Ngapuke** [InnoSpectra/ISC_NIRScan_Tiva_FW#3]
I've just updated the firmware on an older NIR-S-G1 (s/n 941R041) to TIVA version 2.6.3 and the Sagitto app finds the device successfully but is unable to connect. If I return to TIVA version 2.4.10 there's not problem.)

However two newer instruments (s/n A52R010 and s/n A47R002) work fine with TIVA version 2.6.3
Not a big deal - just thought I'd let you know

![File (10)](https://github.com/InnoSpectra/ISC_NIRScan_Tiva_FW_STD/assets/16195729/f8178522-59f4-4ca2-b496-848bf58e99f3)
![File (11)](https://github.com/InnoSpectra/ISC_NIRScan_Tiva_FW_STD/assets/16195729/7a1715ef-40cd-48ff-af17-553d1f3cbb1f)

**Comment by JeremyHsieh** [comment]
Thanks for the feedback. For the older NIR-S-G1 (s/n 941R041), maybe the cell phone kept the old Tiva BLE services cache. Have you tried to manually switch off the cell phone Bluetooth and then on (through Setting, not on the short-cut) after upgrade to Tiva v2.6.3 and connect  again? Or reboot the cell phone will be also an option. Let us know if you have any success with it.

**Comment by JeremyHsieh** [comment]
You can also refer to the demo video - https://youtube.com/shorts/axjdSLjmuLo which shows how to manually switch the cell phone Bluetooth off and on.

**Comment by Ngapuke** [comment]
>Have you tried to manually switch off the cell phone Bluetooth and then on (through Setting, not on the short-cut) after upgrade to Tiva v2.6.3 and connect again?

This solved it - thanks Jeremy
